# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

url: "https://benjamin-owusu.github.io"  # <-- Your GitHub Pages URL
baseurl: ""  # <-- Empty because you're using a user/organization site (no subfolder)

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Benjamin Owusu"  # <-- Add your site title here, not just a space.
email: "Benny.owusuk@gmx.de"
description: "I am Econ Postdoc. I am interested in applied statistics/econometrics, causal inference, and macroeconomics"
twitter_username: "benjamin_owusu"  # <-- Add your Twitter username if available
github_username: "Benjamin-Owusu"
minimal_mistakes_skin: "default"  # <-- Default skin for minimal mistakes theme
search: true  # <-- Enable search on your site

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/  # <-- Keep this as it is for category-based post URLs
paginate: 5  # Amount of posts to show per page
paginate_path: /page:num/
timezone: "Europe/Berlin"  # <-- Add your timezone if you'd like

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  #name: "Benjamin Owusu"
  avatar: "/assets/images/bio-photo.jpg"  # <-- Update your avatar if you have one
  bio: "An applied economist with passion for research and data analysis/data science."
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/benjamin-owusu-phd-b6390258/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Benjamin-Owusu"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

footer:
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/benjamin-owusu-phd-b6390258/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Benjamin-Owusu"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Add to _config.yml

# Custom CSS
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: single
      author_profile: true
      header_scripts:
        - /assets/images/css/custom.css
  - scope:
      path: ""
      type: "pages"
    values:
      layout: single
      author_profile: true
      header_scripts:
        - /assets/images/css/custom.css
    sass:
      style: compressed


   
